- name: Deploy HDS
  command: kubectl apply -f repos/hds-container/k8s/{{ item }}.yaml
  with_items:
  - namespace
  - pvc
  - nfs
  - cron

- name: Deploy Helium Events infra
  command: kubectl apply -f repos/heliumevents/k8s/runonce/{{ item }}.yaml
  with_items:
  - namespace
  - nfs
  - storage

- name: Deploy Helium Events workloads
  command: kubectl apply -f repos/heliumevents/k8s/{{ item }}.yaml
  with_items:
  - services
  - elasticsearch
  - filebeat-kubernetes
  - metricbeat-kubernetes
  - kibana
  - cron
  - cron-miner-info
  - cron-miner-gap
  - cron-price-usd
  - cron-price-gbp
  - cron-james
  - cron-davey
  - cron-ill