- name: Download k3sup
  get_url:
    url: https://get.k3sup.dev 
    dest: "{{ k3sup_download_location }}"

- name: Bootstrap k3sup
  command: sh "{{ k3sup_download_location }}"

- name: Clean up
  file: 
    path: "{{ k3sup_download_location }}"
    state: absent
  
- name: Copy to bin
  become: yes
  when: inventory_hostname not in groups['virtualbox']
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/k3sup
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: u=rwx,g=rx,o=r
    with_fileglob: (k3sup|k3sup-arm64) # depending on whether it's an ARM or AMD platform, different files are downloaded

- name: Load master key (so we can use it in the next step)
  slurp:
    src: '.ssh/id_rsa.pub'
  register: master_key

- name: Authorize self to SSH to self (authorise own key)
  authorized_key:
    user: ubuntu
    state: present
    key: "{{ master_key['content'] | b64decode }}"
    path: "/home/ubuntu/.ssh/authorized_keys"


- name: Install master node - k3sup
  become: yes
  become_method: sudo
  command: "./k3sup install --local --k3s-version={{ version }}"

- name: Make config file readable by ubuntu so we can run kubectl without sudo
  become: yes
  file:
    path: /etc/rancher/k3s/k3s.yaml
    owner: ubuntu
    group: ubuntu
    